export const SWAP_WIDGET_CONFING = {
  integratorId: process.env.NEXT_PUBLIC_ITR_ID,
  apiUrl: process.env.NEXT_PUBLIC_SQ_API,
  themeType: 'dark',
  theme: {
    borderRadius: {
      'button-lg-primary': '1.25rem',
      'button-lg-secondary': '1.25rem',
      'button-lg-tertiary': '1.25rem',
      'button-md-primary': '0.9375rem',
      'button-md-secondary': '0.9375rem',
      'button-md-tertiary': '0.9375rem',
      'button-sm-primary': '1.25rem',
      'button-sm-secondary': '1.25rem',
      'button-sm-tertiary': '1.25rem',
      container: '1.25rem',
      input: '0.9375rem',
      'menu-sm': '0.65rem',
      'menu-lg': '0.65rem',
      modal: '1.25rem'
    },
    fontSize: {
      caption: '0.75rem',
      'body-small': '1rem',
      'body-medium': '1.25rem',
      'body-large': '1.5rem',
      'heading-small': '1.8rem',
      'heading-medium': '2.75rem',
      'heading-large': '3.6rem'
    },
    fontWeight: {
      caption: '400',
      'body-small': '400',
      'body-medium': '400',
      'body-large': '400',
      'heading-small': '400',
      'heading-medium': '400',
      'heading-large': '400'
    },
    fontFamily: {
      'squid-main': 'Public Sans, sans-serif'
    },
    boxShadow: {
      container: '0px 2px 4px 0px rgba(0, 0, 0, 0.20), 0px 5px 50px -1px rgba(0, 0, 0, 0.33)'
    },
    color: {
      'grey-100': '#FBFBFD',
      'grey-200': '#EDEFF3',
      'grey-300': '#D1D6E0',
      'grey-400': '#A7ABBE',
      'grey-500': '#DBDBDB',
      'grey-600': '#676B7E',
      'grey-700': '#4C515D',
      'grey-800': '#152341',
      'grey-900': 'transparent',
      'royal-300': '#8fe0f7',
      'royal-400': '#67cbe7',
      'royal-500': '#22cef9',
      'royal-600': '#38a6c5',
      'royal-700': '#2689a5',
      'status-positive': '#7AE870',
      'status-negative': '#FF4D5B',
      'status-partial': '#F3AF25',
      'highlight-700': '#E4FE53',
      'animation-bg': '#7e5af7',
      'animation-text': '#FBFBFD',
      'button-lg-primary-bg': '#7e5af7',
      'button-lg-primary-text': '#FBFBFD',
      'button-lg-secondary-bg': '#FBFBFD',
      'button-lg-secondary-text': '#292C32',
      'button-lg-tertiary-bg': '#292C32',
      'button-lg-tertiary-text': '#D1D6E0',
      'button-md-primary-bg': '#7e5af7',
      'button-md-primary-text': '#FBFBFD',
      'button-md-secondary-bg': '#FBFBFD',
      'button-md-secondary-text': '#292C32',
      'button-md-tertiary-bg': '#292C32',
      'button-md-tertiary-text': '#D1D6E0',
      'button-sm-primary-bg': '#7e5af7',
      'button-sm-primary-text': '#FBFBFD',
      'button-sm-secondary-bg': '#FBFBFD',
      'button-sm-secondary-text': '#292C32',
      'button-sm-tertiary-bg': '#292C32',
      'button-sm-tertiary-text': '#D1D6E0',
      'input-bg': '#17191C',
      'input-placeholder': '#676B7E',
      'input-text': '#D1D6E0',
      'input-selection': '#D1D6E0',
      'menu-bg': '#152341',
      'menu-text': '#FBFBFDA8',
      'menu-backdrop': '#FBFBFD1A',
      'modal-backdrop': '#17191C54'
    }
  },
  priceImpactWarnings: {
    warning: 3,
    critical: 5
  },
  loadPreviousStateFromLocalStorage: true
}
